#!/usr/bin/env bash

# =============================================================================
# NAME        : bash_env
# DESCRIPTION : 
# AUTHOR      : Adam Compton
# DATE CREATED: 2024-12-08 19:57:22
# =============================================================================
# EDIT HISTORY:
# DATE                 | EDITED BY    | DESCRIPTION OF CHANGE
# ---------------------|--------------|----------------------------------------
# 2024-12-08 19:57:22  | Adam Compton | Initial creation.
# =============================================================================

# Guard to prevent multiple sourcing
if [[ -z "${BASH_ENV_LOADED:-}" ]]; then
    declare -g BASH_ENV_LOADED=true

    # define default editor
    export EDITOR="vim"

    # enable LS colored output
    export CLICOLOR=1

    # define colors for macOS
    export LSCOLORS=exfxcxdxbxegedabagacxx

    # define colors for Linux
    export LS_COLORS="di=34:ln=35:so=32:pi=33:ex=31:bd=34:cd=34:su=0;41:sg=0;46:tw=0;42:ow=33"

    # Apply LS_COLORS to the environment
    eval $(dircolors -b)

    # If you want to use LS_COLORS in completion (for example, with GNU Readline):
    if [[ "$SHELL" == "/bin/bash" ]]; then
        bind 'set colored-stats on'
    fi

    # configure bat  (bat > cat)
    export BAT_PAGER="less -R"
    export BAT_THEME="ansi"
fi
