#!/usr/bin/env bash

# =============================================================================
# NAME        : bash_prompt
# DESCRIPTION : 
# AUTHOR      : Adam Compton
# DATE CREATED: 2024-12-08 19:57:22
# =============================================================================
# EDIT HISTORY:
# DATE                 | EDITED BY    | DESCRIPTION OF CHANGE
# ---------------------|--------------|----------------------------------------
# 2024-12-08 19:57:22  | Adam Compton | Initial creation.
# =============================================================================

# Guard to prevent multiple sourcing
if [[ -z "${BASH_PROMPT_LOADED:-}" ]]; then
    declare -g BASH_PROMPT_LOADED=true

    # Define colors
    light_green='\[\e[1;32m\]'
    light_blue='\[\e[1;36m\]'
    blue='\[\e[34m\]'
    light_red='\[\e[1;31m\]'
    yellow='\[\e[1;33m\]'
    white='\[\e[1;37m\]'
    reset='\[\e[0m\]'

    # VARIABLES for IPs
    PROMPT_LOCAL_IP=""
    PROMPT_EXTERNAL_IP=""
    LAST_IP_CHECK=0

    # Function to assist in displaying the prompt
    source ~/.bash_prompt_funcs

    function gen_prompt(){
        # Get the active screen session name, if any
        session_name=$(get_session_name)
    #
    #    # If there's an active session, prepend its name to the last command in history
    #    if [[ -n "$session_name" ]]; then
    #        last_command=$(history 1 | sed 's/^[[:space:]]*[0-9]\+[[:space:]]\+//')
    #        # Write the modified command to the history file
    #        if [[ -n "$last_command" ]]; then
    #            # Prepend the session name and write to the history file
    #            echo "<$session_name> $last_command" >> ~/.history_sessions
    #        fi
    #        # Append each command to the history file immediately
    #        history -a; history -n;
    #    else
    #        # Append each command to the history file immediately
    #        {
    #            flock 200
    #            history -a
    #            history -n
    #            history | sed 's/^[[:space:]]*[0-9]\+[[:space:]]\+//' > ~/.history_temp
    #            cat ~/.history_temp ~/.history_all | sort -u -V > ~/.history_all
    #            rm ~/.history_temp
    #        } 200>~/.history_all.lock
    #    fi

        # Define prompt format
        PS1="\n"

        # SCREEN SESSION STATUS
        PS1+="$(check_session)"

        # KERBEROS CREDENTIAL CACHE
        PS1+="$(check_kerb_ccache)"

        # PYTHON VENV
        PS1+="$(check_venv)"

        # DATE TIME
        PS1+="${white}[${light_green}\D{%m-%d-%Y} \t${white}]━"

        # INTERNAL IP
        PS1+="${white}[${light_blue}$(get_local_ip)${white}]━"

        # EXTERNAL IP
        #PS1+="${white}[ext:$blue}$(get_external_ip)${white}]━"

        # USER@FQDN
        PS1+="${white}[${light_red}\u@\h${white}]\n"

        # PATH
        PS1+="${white}┗━> [${yellow}\w${white}]${reset} \$ \[$(tput sgr0)\]"

        # Set the prompt
        export PS1="$PS1"
    }

    PROMPT_COMMAND=gen_prompt

    # Make sure the proper date/time is always shown
    if [ -f ~/.bash-preexec.sh ]; then
        source ~/.bash-preexec.sh
    fi

    preexec() {
        date_time_stamp=$(date +"[%D %T]")
        echo
        echo "$date_time_stamp # $1"
        echo
    }
fi