#!/usr/bin/env bash

# =============================================================================
# NAME        : path_env
# DESCRIPTION : 
# AUTHOR      : Adam Compton
# DATE CREATED: 2024-12-08 19:57:22
# =============================================================================
# EDIT HISTORY:
# DATE                 | EDITED BY    | DESCRIPTION OF CHANGE
# ---------------------|--------------|----------------------------------------
# 2024-12-08 19:57:22  | Adam Compton | Initial creation.
# =============================================================================

# Guard to prevent multiple sourcing
if [[ -z "${PATH_ENV_LOADED:-}" ]]; then
    declare -g PATH_ENV_LOADED=true

    export DATA_DIR="${HOME}/DATA"

    export CONFIG_DIR="$DATA_DIR/CONFIG"
    export TOOLS_DIR="$DATA_DIR/TOOLS"
    export SCRIPTS_DIR="$DATA_DIR/TOOLS/SCRIPTS"
    export LOGS_DIR="$DATA_DIR/LOGS"
    export OUTPUT_DIR="$DATA_DIR/OUTPUT"
    export LOOT_DIR="$DATA_DIR/LOOT"
    export BACKUP_DIR="${DATA_DIR}/BACKUP"
    export TASKS_DIR="$DATA_DIR/TASKS"
fi
