#!/usr/bin/env bash
set -uo pipefail

# =============================================================================
# NAME        : path_env
# DESCRIPTION :
# AUTHOR      : Adam Compton
# DATE CREATED: 2024-12-08 19:57:22
# =============================================================================
# EDIT HISTORY:
# DATE                 | EDITED BY    | DESCRIPTION OF CHANGE
# ---------------------|--------------|----------------------------------------
# 2024-12-08 19:57:22  | Adam Compton | Initial creation.
# =============================================================================

# Guard to prevent multiple sourcing
if [[ -z "${PATH_ENV_LOADED:-}" ]]; then
    declare -g PATH_ENV_LOADED=true

    # BASH Directory
    export BASH_DIR="${HOME}/.config/bash"
    export BASH_LOG_DIR="${BASH_DIR}/log"

    # Ensure the BASH directory exists
    if [[ ! -d "${BASH_DIR}" ]]; then
        mkdir -p "${BASH_DIR}" || {
            echo "Failed to create directory: ${BASH_DIR}"
            exit 1
        }
        info "Created directory: ${BASH_DIR}"
    fi

    # Ensure the BASH directory exists
    if [[ ! -d "${BASH_LOG_DIR}" ]]; then
        mkdir -p "${BASH_LOG_DIR}" || {
            echo "Failed to create directory: ${BASH_LOG_DIR}"
            exit 1
        }
        info "Created directory: ${BASH_LOG_DIR}"
    fi

    # PENTEST Directories
    export PENTEST_DIR="${HOME}/.config/pentest"
    export DATA_DIR="${HOME}/DATA"
    export CONFIG_DIR="${DATA_DIR}/CONFIG"
    export TOOLS_DIR="${DATA_DIR}/TOOLS"
    export SCRIPTS_DIR="${DATA_DIR}/TOOLS/SCRIPTS"
    export LOGS_DIR="${DATA_DIR}/LOGS"
    export OUTPUT_DIR="${DATA_DIR}/OUTPUT"
    export LOOT_DIR="${DATA_DIR}/LOOT"
    export BACKUP_DIR="${DATA_DIR}/BACKUP"
    export TASKS_DIR="${DATA_DIR}/TASKS"

    # PENTEST Files
    export ENV_FILE="${PENTEST_DIR}/pentest.env"
    export ALIAS_FILE="${PENTEST_DIR}/pentest.alias"
    export KEYS_FILE="${PENTEST_DIR}/pentest.keys"
    export LOG_FILE="${PENTEST_DIR}/pentest.log"
    export MENU_TIMESTAMP_FILE="${PENTEST_DIR}/menu_timestamps"

    # Ensure the PENTEST directory exists
    if [[ ! -d "${PENTEST_DIR}" ]]; then
        mkdir -p "${PENTEST_DIR}" || {
            echo "Failed to create directory: ${PENTEST_DIR}"
            exit 1
        }
        info "Created directory: ${PENTEST_DIR}"
    fi

    # Ensure the DATA directory exists
    if [[ ! -d "${DATA_DIR}" ]]; then
        mkdir -p "${DATA_DIR}" || {
            echo "Failed to create directory: ${DATA_DIR}"
            exit 1
        }
        info "Created directory: ${DATA_DIR}"
    fi

    # -----------------------------
    # API/License Keys Configuration
    # -----------------------------

    if [[ -f "${KEYS_FILE}" ]]; then
        source "${KEYS_FILE}"
    else
        echo "File not found: ${KEYS_FILE}. Skipping sourcing."
    fi
fi
