#cloud-config
package_update: true
packages:
 - bat
 - eza
 - ncat
 - proxychains4
 - fzf
 - git
runcmd:
 - git clone https://github.com/tatanus/BASH.git /opt/BASH
 - echo "hi" > /hi.txt
 - cd /opt/BASH/ && export HOME=/root/ && bash SetupBashAuto.sh -bash > /opt/bash_debug_output.log 2>&1
