name: Coverage Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    name: Generate Coverage and Send to Coveralls
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install kcov
        run: |
          sudo apt update
          sudo apt install -y kcov

      # Run kcov to generate coverage
      - name: Generate Coverage
        run: |
          mkdir -p coverage
          for script in $(find . -name "*.sh"); do
            kcov coverage/ "$script" || true
          done

      # Upload to Coveralls
      - name: Upload Coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          curl -F 'json_file=@coverage/coverage.json' https://coveralls.io/api/v1/jobs
