name: Bash Project CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Bash Scripts with ShellCheck
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install ShellCheck
      - name: Install ShellCheck
        run: |
          sudo apt update
          sudo apt install -y shellcheck

      # Run ShellCheck on all scripts
      - name: Run ShellCheck
        run: |
          find . -name "*.sh" -print0 | xargs -0 shellcheck

  format:
    name: Check Formatting with shfmt
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install shfmt
      - name: Install shfmt
        run: |
          sudo apt update
          sudo apt install -y shfmt

      # Run shfmt to check formatting
      - name: Run shfmt
        run: |
          shfmt -d -i 4 -ci -bn -kp .

  # test:
  #   name: Run Unit Tests with BATS
  #   runs-on: ubuntu-latest

  #   steps:
  #     # Checkout code
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     # Install BATS
  #     - name: Install BATS
  #       run: |
  #         sudo apt update
  #         sudo apt install -y bats

  #     # Run BATS tests
  #     - name: Run BATS Tests
  #       run: |
  #         bats test/

  validate_permissions:
    name: Validate File Permissions and Shebangs
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Ensure all shell scripts are executable
      - name: Ensure Executable Permissions
        run: |
          find . -name "*.sh" -exec chmod +x {} \;

      # Validate all scripts have a shebang
      - name: Validate Shebangs
        run: |
          missing_shebangs=$(find . -name "*.sh" ! -path "./dot/bash-preexec.sh" ! -path "./another/ignored-file.sh" -exec sh -c 'head -n 1 "$1" | grep -q "^#!" || echo "Missing shebang: $1"' _ {} \;)
          if [[ -n "$missing_shebangs" ]]; then
            echo "The following files are missing a shebang:"
            echo "$missing_shebangs"
            exit 1
          fi
