name: ShellCheck Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Bash Scripts
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install ShellCheck
      - name: Install ShellCheck
        run: |
          sudo apt update
          sudo apt install -y shellcheck

      # Run ShellCheck on all scripts
      - name: Run ShellCheck
        run: |
          find . -name "*.sh" -print0 | xargs -0 shellcheck 
